// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "super_super_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol TXSSuperSuperListener;

namespace djinni_generated {

class SuperSuperListener
{
public:
    using CppType = std::shared_ptr<::textsort::SuperSuperListener>;
    using CppOptType = std::shared_ptr<::textsort::SuperSuperListener>;
    using ObjcType = id<TXSSuperSuperListener>;

    using Boxed = SuperSuperListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

