// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSSuperSuperListener+Private.h"
#import "TXSSuperSuperListener.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class SuperSuperListener::ObjcProxy final
: public ::textsort::SuperSuperListener
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::SuperSuperListener;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void updateSuper() override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() updateSuper];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto SuperSuperListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto SuperSuperListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
