// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSItemList.h"
#import <Foundation/Foundation.h>


@protocol TXSSuperListtener

- (void)update:(nonnull TXSItemList *)items;

@end
