// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSItemList.h"
#import "TXSSuperSuperListener.h"
#import <Foundation/Foundation.h>


@interface TXSSuperListtener : NSObject

- (void)update:(nonnull TXSItemList *)items;

@end
