// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSItemList.h"
#import "TXSSuperListtener.h"
#import <Foundation/Foundation.h>

extern int32_t const TXSTextboxListenerVersion;
extern NSString * __nonnull const TXSTextboxListenerStringtest;

@protocol TXSTextboxListener <TXSSuperListtener>

/**update(items: item_list); */
- (void)updateNew:(nonnull TXSItemList *)items;

@end
