// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSItemList.h"
#import "TXSSuperListtener.h"
#import <Foundation/Foundation.h>


@protocol TXSTextboxListener <TXSSuperListtener>

/**update(items: item_list); */
- (void)updateNew:(nonnull TXSItemList *)items;

@end
