// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "NativeSuperSuperListener.hpp"  // my header

namespace djinni_generated {

NativeSuperSuperListener::NativeSuperSuperListener() : ::djinni::JniInterface<::textsort::SuperSuperListener, NativeSuperSuperListener>() {}

NativeSuperSuperListener::~NativeSuperSuperListener() = default;

NativeSuperSuperListener::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeSuperSuperListener::JavaProxy::~JavaProxy() = default;

void NativeSuperSuperListener::JavaProxy::updateSuper() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeSuperSuperListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_updateSuper);
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
