// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <string>
#include <utility>
#include <vector>

namespace textsort {

struct ItemList final {
    std::vector<std::string> items;

    friend bool operator==(const ItemList& lhs, const ItemList& rhs);
    friend bool operator!=(const ItemList& lhs, const ItemList& rhs);

    ItemList(std::vector<std::string> items_)
    : items(std::move(items_))
    {}
};

}  // namespace textsort
