// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

namespace textsort {

class SuperSuperListener {
public:
    virtual ~SuperSuperListener() {}

    virtual void updateSuper() {}
};

}  // namespace textsort
