// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "super_super_listener.hpp"

namespace textsort {

class SuperSuperListener;
struct ItemList;

class SuperListtener : public SuperSuperListener {
public:
    virtual ~SuperListtener() {}

    virtual void update(const ItemList & items) {}
};

}  // namespace textsort
