// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

namespace textsort {

struct ItemList;

class SuperListtener {
public:
    virtual ~SuperListtener() {}

    virtual void update(const ItemList & items) {}
};

}  // namespace textsort
