// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "textbox_listener.hpp"  // my header
#include "item_list.hpp"

#ifdef __ANDROID__
#include "NativeTextboxListener.hpp"
#include "djinni_proxy_constructor.hpp"

#define CREATE_PROXY_OBJC(PTR) \
    jobject obj = ::djinni::ProxyConstructorMap::get()->createObject("textbox_listener"); \
    if (obj) { \
        PTR = ::djinni_generated::NativeTextboxListener::toCpp(::djinni::jniGetThreadEnv(), obj); \
    }
#endif

#ifdef __APPLE__
#include "TXSConstructProxy.h"
#define CREATE_PROXY_OBJC(PTR) \
    PTR = createTXSTextboxListener();
#endif

#ifndef CREATE_PROXY_OBJC
#define CREATE_PROXY_OBJC(PTR)
#endif


namespace textsort {

void TextboxListener::init() {
    CREATE_PROXY_OBJC(this->_objPtr);
}

int32_t const TextboxListener::VERSION = 1;

std::string const TextboxListener::STRINGTEST = {"123123"};

}  // namespace textsort
