// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "super_listtener.hpp"

namespace textsort {

class SuperListtener;
struct ItemList;

class TextboxListener : public SuperListtener {
public:
    virtual ~TextboxListener() {}

    /**update(items: item_list); */
    virtual void updateNew(const ItemList & items) {}
};

}  // namespace textsort
