// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

/*package*/ interface SuperSuperListener {
    public void updateSuper();
}
