// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

/*package*/ interface SuperListtener {
    public void update(ItemList items);
}
