// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

/*package*/ interface TextboxListener extends SuperListtener {
    public static final int VERSION = 1;

    public static final String STRINGTEST = "123123";

    /**update(items: item_list); */
    public void updateNew(ItemList items);
}
